version: 2

models:
  - name: dim_customers
    description: Customer dimension table
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1000
          max_value: 200000
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_to_exist

  - name: fct_orders
    description: Orders fact table
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 10000
          max_value: 200000
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_to_exist
      
      - name: order_status
        description: Current status of the order
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['delivered', 'shipped', 'processing', 'canceled', 'unavailable', 'invoiced', 'created', 'approved']