version: 2

models:
  - name: int_customer_orders
    description: Intermediate customer orders aggregation
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1000
          max_value: 200000
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_to_exist

  - name: int_order_details
    description: Intermediate order details with enriched information
    tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 10000
          max_value: 200000
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_to_exist