version: 2

sources:
  - name: olist
    description: Brazilian e-commerce dataset
    database: brazil-olist
    schema: Olist
    tables:
      - name: customer
        description: Customer information
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
      
      - name: orders
        description: Order information
        columns:
          - name: order_id
            description: Unique order identifier
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Customer who placed the order
            tests:
              - not_null
              - relationships:
                  to: source('olist', 'customer')
                  field: customer_id
      
      - name: order_items
        description: Items within each order
        columns:
          - name: order_id
            description: Order identifier
            tests:
              - not_null
              - relationships:
                  to: source('olist', 'orders')
                  field: order_id
      
      - name: order_payments
        description: Payment information for orders
      - name: products
        description: Product catalog
      - name: sellers
        description: Seller information
      - name: geolocation
        description: Geographic coordinates
      - name: translations
        description: Category name translations